name = "routing-backend"
main = "src/index.js"
compatibility_date = "2023-12-01"

routes = [
  { pattern = "ritualx-dev.ritual-app.co/backend/*", zone_name = "ritual-app.co" }
]

[env.production]
routes = [
  { pattern = "ritualx.ritual-app.co/backend/*", zone_name = "ritual-app.co" }
]

